name = "ai-image-generator-api"
main = "api-only.js"
compatibility_date = "2024-08-24"
compatibility_flags = ["nodejs_compat"]

# Production environment
[env.production]
name = "ai-image-generator-api"